### ISSUE TITLE
Hearts card missing

### ISSUE THREAD

**Issue by peakpeak-github** [petrzmax/CPO#1]
Why is there no definition for hearts cards?
```
struct cardsStruct
{
    int membership = 0; // Belonging to a particular segment
    int spade = 0; // Spade
    int diamond = 0; // Diamond
    int club = 0; // Club
    int value = 0;
};
```

**Comment by petrzmax** [comment]
Hi!,
This code was written for a specific data set of cards. In my case there was no hearts :) 
For sure it would be required for a real use case.

Best regards from Poland,
Artur
